module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.23.0

require github.com/google/wire v0.6.0 // cmd/wire

require golang.org/x/tools v0.35.0 // explicit override for Go 1.24 compatibility
