{
 "title": "Azure / Insights / Applications - Failures - 1. Operations",
 "description": "The dashboard provides insights of operation failures through Application Insights.",
 "tags": [ "Azure-AppInsights-Failures" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   },
   { "name": "res", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" },
   {
    "name": "result_code",
    "label": "Result Code",
    "query": {}
   },
   {
    "name": "operation_name",
    "label": "Operation Names",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Failures - Operations" } },
  {
   "title": "Application Insights - Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Failed Requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where \"All\" in ($operation_name) or operation_Name in ($operation_name)\n| where \"All\" in ($result_code) or resultCode in ($result_code)\n| summarize FailedCount=sumif(itemCount, success == false) by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 5 response codes",
   "type": "table",
   "description": "Click on a result code to filter this dashboard.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where success == false\n| where \"All\" in ($operation_name) or operation_Name in ($operation_name)\n| summarize Count=sum(itemCount) by [\"Result Code\"]=resultCode\n| top 5 by Count desc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 5 exception types",
   "type": "table",
   "description": "Click on an type to open the exceptions dashboard.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nexceptions\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| summarize Count=sum(itemCount) by type\n| top 5 by Count desc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Response codes (count)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where \"All\" in ($operation_name) or operation_Name in ($operation_name)\n| where \"All\" in ($result_code) or resultCode in ($result_code)\n| where client_Type != \"Browser\"\n| where success == false\n| summarize ResultCode = sum(itemCount) by resultCode, bin(timestamp, $__interval)\n| sort by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 5 failed dependencies",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where success == false\n| summarize Count=sum(itemCount) by type\n| top 5 by Count desc\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where \"All\" in ($operation_name) or operation_Name in ($operation_name)\n| where \"All\" in ($result_code) or resultCode in ($result_code)\n// calculate average request duration for all requests\n| summarize Count = count() by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "All Failed Operations (Count) matching Result code $result_code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where \"All\" in ($result_code) or resultCode in ($result_code)\n| where client_Type != \"Browser\"\n| summarize failedCount=sumif(itemCount, success == false)\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Number of failed transactions matching $operation_name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "requests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where \"All\" in ($result_code) or resultCode in ($result_code)\n| where client_Type != \"Browser\"\n| where \"All\" in ($operation_name) or operation_Name in ($operation_name)\n| summarize failedCount=sumif(itemCount, success == false)\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 10 Failed Operation Name List",
   "type": "table",
   "description": "Click on the Operation name to filter dashboard.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let dataset =\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\";\ndataset\n| summarize\n    [\"Failed count\"]=sumif(itemCount, success == 'False' and (\"All\" in ($result_code) or resultCode in ($result_code))),\n    [\"Impacted users\"]=dcountif(user_Id, success == 'False' and (\"All\" in ($result_code) or resultCode in ($result_code))),\n    [\"Total count\"]=sum(itemCount)\n| project [\"Operation name\"]=\"All\", [\"Failed count\"], [\"Impacted users\"], [\"Total count\"]\n| union (dataset| summarize\n    [\"Failed count\"]=sumif(itemCount, success == 'False' and (\"All\" in ($result_code) or resultCode in ($result_code))),\n    [\"Impacted users\"]=dcountif(user_Id, success == 'False' and (\"All\" in ($result_code) or resultCode in ($result_code))),\n    [\"Total count\"]=sum(itemCount)\n    by [\"Operation name\"]=operation_Name\n| where [\"Failed count\"] > 0\n| top 10 by [\"Failed count\"] desc)\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table",
      "dashboardTime": false
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 20 Sample Failed Operations matching $operation_name by relevance",
   "type": "table",
   "description": "Click on the OperationID or Name to view trace details in explorer.",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 27 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let min_length_8 = (s: string) {\n    let len = strlen(s);\n    case(len == 1, strcat(s, s, s, s, s, s, s, s),\n        len == 2 or len == 3, strcat(s, s, s, s),\n        len == 4 or len == 5 or len == 6 or len == 7, strcat(s, s),\n        s)\n};\nlet ai_hash = (s: string) {\n    abs(toint(__hash_djb2(min_length_8(s))))\n};\n\nrequests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where \"All\" in ($operation_name) or operation_Name in ($operation_name)\n| where \"All\" in ($result_code) or resultCode in ($result_code)\n| where success == 'False'\n| project Name = operation_Name, [\"Response Code\"] = resultCode, [\"Response Time\"] = duration, OperationID = operation_Id, Score=ai_hash(operation_Id)\n| top 20 by Score asc\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}